default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: go-to-guy

test:
  <<: *default
  database: go-to-guy

production:
  <<: *default
  database: the-go-to-guy
  username: ruby-rails samp
  password: password
